[font]
size = 18.0
normal.family = "FiraCode Nerd Font"
normal.style = "Light"
offset.y = 1


[colors.primary]
background = "0x24273a"
foreground = "0xcad3f5"

[colors.normal]
black   = "0x494d64"
red     = "0xed8796"
green   = "0xa6da95"
yellow  = "0xeed49f"
blue    = "0x8aadf4"
magenta = "0xf5bde6"
cyan    = "0x8bd5ca"
white   = "0xb8c0e0"

[colors.bright]
black   = "0x5b6078"
red     = "0xed8796"
green   = "0xa6da95"
yellow  = "0xeed49f"
blue    = "0x8aadf4"
magenta = "0xf5bde6"
cyan    = "0x8bd5ca"
white   = "0xa5adcb"
