unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -n C-S-Left previous-window
bind-key -n C-S-Right next-window

bind "'" split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind-key x kill-pane
bind C-o popup -E -d "#{pane_current_path}" -w 90% -h 90% "opencode"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -ga status-right "#{E:@catppuccin_status_directory}"
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ga status-right "#{E:@catppuccin_status_date_time}"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 20
set -g renumber-windows on

run '~/.tmux/plugins/tpm/tpm'
